#!/usr/bin/env perl

if ($ARGV > 1) {
    $encoding = @ARGV[1];
} else {
    $encoding = "zh_CN.UTF-8";
}

$node = `mdconfig -a -t vnode -f "@ARGV[0]"`;
chop($node);

if ($node !~ /md\d+/)
{
    die "mdconfig failed.";
}
print "Mounting /dev/$node to /cdrom\n";

$ret = system("mount_cd9660 -o ro,-L=$encoding /dev/$node /cdrom");

if ($ret != 0)
{
    print "mount failed\n";
    system("mdconfig -d -u $node");
}


$ret
